// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for IOS - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ZZUNTxskk0kF11UPCNRMTJ2-WNPO_b4',
    appId: '1:360544205843:android:4f4d766c5548f320db53e6',
    messagingSenderId: '360544205843',
    projectId: 'meus-animais',
    databaseURL: 'https://meus-animais-default-rtdb.firebaseio.com',
    storageBucket: 'meus-animais.appspot.com',
  );

  /*
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1CRsXRyXkpAOiz7b6FFKwxfGrhDG0DP8',
    appId: '1:207464663642:ios:f85e9740574e9640e3a663',
    messagingSenderId: '207464663642',
    projectId: 'orgalive-f1e45',
    databaseURL: 'https://orgalive-f1e45-default-rtdb.firebaseio.com',
    storageBucket: 'orgalive-f1e45.appspot.com',
    androidClientId: '207464663642-3u5o8do9l550s9q4tq0a032i4tmipca0.apps.googleusercontent.com',
    iosClientId: '207464663642-0at3cll22j985qfudg914t5li7iadlbu.apps.googleusercontent.com',
    iosBundleId: 'br.com.orgalive',
  );
  */

}