name: meus_animais
description: Cuide de seus create_pets, desde os dias que tomam vacinas até a quantidade de banhos que tomam.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+11

environment:
  sdk: ">=2.17.3 <3.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  firebase_performance: ^0.8.0+14
  flutter_secure_storage: ^5.0.2
  font_awesome_flutter: ^10.1.0
  firebase_crashlytics: ^2.8.2
  flutter_masked_text2: ^0.9.1
  firebase_analytics: ^9.1.10
  shimmer_animation: ^2.1.0+1
  firebase_storage: ^10.2.18
  connectivity_plus: ^2.3.5
  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  flutter_mobx: ^2.0.6+1
  google_nav_bar: ^5.0.6
  image_picker: ^0.8.5+3
  find_dropdown: ^1.0.0
  injectable: ^1.5.3
  image_crop: ^0.4.0
  provider: ^6.0.3
  get_it: ^7.2.0
  mobx: ^2.0.7+4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_native_splash: ^2.2.3+1
  injectable_generator: ^1.5.3
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.0.7
  test: ^1.21.1

# configuracao da splash
flutter_native_splash:
  color: "#363435"
  image: assets/img/loading.jpg
  android: true
  ios: true
  fullscreen: true

# The following section is specific to Flutter packages.
flutter:

  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
