name: meus_animais
description: "Tome nota dos cuidados especiais que seu pet precisa!"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.2+41

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  myne_find_dropdown:
    git:
      url: https://github.com/TiagoBruckmann/myne_find_dropdown.git
      ref: V0.0.1

  flutter_launcher_icons: ^0.14.4
  firebase_performance: ^0.11.0+1
  font_awesome_flutter: ^10.10.0
  firebase_crashlytics: ^5.0.1
  firebase_app_check: ^0.4.0+1
  flutter_masked_text2: ^0.9.1
  firebase_analytics: ^12.0.1
  shimmer_animation: ^2.2.2
  firebase_storage: ^13.0.1
  onesignal_flutter: ^5.3.4
  connectivity_plus: ^6.1.5
  device_info_plus: ^11.5.0
  new_version_plus: ^0.1.1
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.8
  crop_your_image: ^1.1.0
  google_nav_bar: ^5.0.7
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  flutter_i18n: ^0.36.3
  image_picker: ^1.2.0
  url_launcher: ^6.3.2
  flutter_mobx: ^2.3.0
  injectable: ^2.5.1
  equatable: ^2.0.7
  provider: ^6.1.5+1
  dartz: ^0.10.1
  get_it: ^8.2.0
  mobx: ^2.5.0
  intl: ^0.20.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.6
  injectable_generator: ^2.8.1
  build_runner: ^2.7.1
  flutter_lints: ^6.0.0
  mobx_codegen: ^2.7.2

# configuracao do launch icon
flutter_launcher_icons:
  image_path: "assets/img/logo1.jpg"
  android: true
  ios: true
  min_sdk_android: 19
  remove_alpha_ios: true
  background_color_ios: "#FFC000"

# configuracao da splash
flutter_native_splash:
  color: "#FFC000"
  color_dark: "#FFC000"
  image: assets/img/logo_splash.png
  image_dark: assets/img/logo_splash.png
  android: true
  ios: true
  fullscreen: true

  android_12:
    image: assets/img/logo_splash.png
    icon_background_color: "#FFC000"
    image_dark: assets/img/logo_splash.png
    icon_background_color_dark: "#FFC000"

  web: false

flutter:

  uses-material-design: true

  assets:
    - assets/languages/
    - assets/img/
